# Generated by Django 3.2.2 on 2021-05-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20210508_1649'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='humidity',
            options={'get_latest_by': ['-date_time'], 'ordering': ['-date_time'], 'verbose_name_plural': 'humidities'},
        ),
        migrations.AlterModelOptions(
            name='temperature',
            options={'get_latest_by': ['-date_time'], 'ordering': ['-date_time']},
        ),
        migrations.RenameField(
            model_name='humidity',
            old_name='humidity',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='temperature',
            old_name='temperature',
            new_name='value',
        ),
        migrations.AlterField(
            model_name='temperature',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
