# Generated by Django 3.2.2 on 2021-05-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20210509_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lightness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('date_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_time'],
                'get_latest_by': ['-date_time'],
            },
        ),
    ]
