# Generated by Django 3.2.2 on 2021-05-18 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20210511_1626'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='humidity',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='lightness',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='temperature',
            managers=[
            ],
        ),
    ]
