# Generated by Django 3.2.2 on 2021-05-18 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_update_temperature', models.BooleanField(default=False)),
                ('update_temperature_times', models.JSONField()),
                ('auto_update_humidity', models.BooleanField(default=False)),
                ('update_humidity_times', models.JSONField()),
                ('auto_update_lightness', models.BooleanField(default=False)),
                ('update_lighntess_times', models.JSONField()),
            ],
        ),
    ]
