# Generated by Django 3.2.2 on 2021-05-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210518_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='update_humidity_times',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='update_lighntess_times',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='update_temperature_times',
        ),
        migrations.AddField(
            model_name='settings',
            name='update_humidity_time1',
            field=models.IntegerField(choices=[(0, ''), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24)], default=0, verbose_name='Update time of humidity'),
        ),
        migrations.AddField(
            model_name='settings',
            name='update_humidity_time2',
            field=models.IntegerField(choices=[(0, ''), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24)], default=0, verbose_name='Update time of humidity'),
        ),
        migrations.AddField(
            model_name='settings',
            name='update_humidity_time3',
            field=models.IntegerField(choices=[(0, ''), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24)], default=0, verbose_name='Update time of humidity'),
        ),
        migrations.AddField(
            model_name='settings',
            name='update_lightness_time1',
            field=models.IntegerField(choices=[(0, ''), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24)], default=0, verbose_name='Update time of lightness'),
        ),
        migrations.AddField(
            model_name='settings',
            name='update_lightness_time2',
            field=models.IntegerField(choices=[(0, ''), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24)], default=0, verbose_name='Update time of lightness'),
        ),
        migrations.AddField(
            model_name='settings',
            name='update_lightness_time3',
            field=models.IntegerField(choices=[(0, ''), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24)], default=0, verbose_name='Update time of lightness'),
        ),
        migrations.AddField(
            model_name='settings',
            name='update_temperature_time1',
            field=models.IntegerField(choices=[(0, ''), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24)], default=0, verbose_name='Update time of temperature'),
        ),
        migrations.AddField(
            model_name='settings',
            name='update_temperature_time2',
            field=models.IntegerField(choices=[(0, ''), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24)], default=0, verbose_name='Update time of temperature'),
        ),
        migrations.AddField(
            model_name='settings',
            name='update_temperature_time3',
            field=models.IntegerField(choices=[(0, ''), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24)], default=0, verbose_name='Update time of temperature'),
        ),
    ]
