# Generated by Django 3.2.2 on 2021-06-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210519_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='move_checker_beeper',
            field=models.BooleanField(default=False, verbose_name='Should Arduino beep when something is moving'),
        ),
        migrations.AddField(
            model_name='settings',
            name='move_checker_email',
            field=models.BooleanField(default=False, verbose_name='Should e-mail be send when something is moving'),
        ),
        migrations.AddField(
            model_name='settings',
            name='move_checker_time',
            field=models.CharField(blank=True, help_text='In which hours motion detector should be on.Values has to be in format hh:mm-hh:mm, divided by commas, f.e. 13:40-15:60', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='auto_update_humidity',
            field=models.BooleanField(default=False, verbose_name='Automatic update of humidity'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='auto_update_lightness',
            field=models.BooleanField(default=False, verbose_name='Automatic update of lightness'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='auto_update_temperature',
            field=models.BooleanField(default=False, verbose_name='Automatic update of temperature'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='update_humidity_time1',
            field=models.IntegerField(choices=[(-1, ''), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (0, 24)], default=-1, verbose_name='Update time of humidity'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='update_humidity_time2',
            field=models.IntegerField(choices=[(-1, ''), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (0, 24)], default=-1, verbose_name='Update time of humidity'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='update_humidity_time3',
            field=models.IntegerField(choices=[(-1, ''), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (0, 24)], default=-1, verbose_name='Update time of humidity'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='update_lightness_time1',
            field=models.IntegerField(choices=[(-1, ''), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (0, 24)], default=-1, verbose_name='Update time of lightness'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='update_lightness_time2',
            field=models.IntegerField(choices=[(-1, ''), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (0, 24)], default=-1, verbose_name='Update time of lightness'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='update_lightness_time3',
            field=models.IntegerField(choices=[(-1, ''), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (0, 24)], default=-1, verbose_name='Update time of lightness'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='update_temperature_time1',
            field=models.IntegerField(choices=[(-1, ''), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (0, 24)], default=-1, verbose_name='Update time of temperature'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='update_temperature_time2',
            field=models.IntegerField(choices=[(-1, ''), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (0, 24)], default=-1, verbose_name='Update time of temperature'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='update_temperature_time3',
            field=models.IntegerField(choices=[(-1, ''), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (0, 24)], default=-1, verbose_name='Update time of temperature'),
        ),
    ]
